version: '2.1'

services:
  redis:
    image: redis:7.2.4
    # restart: always
    container_name: redis
    environment:
      - REDIS_PASSWORD=example
    ports:
      - "6379:6379"
    networks:
      - default

networks:
  default:
    external:
      name: nginx_local