version: '2.1'

services:
  node:
    container_name: node-hello-world
    image: node:20
    working_dir: /app
    command: "./run.sh"
    ports:
      - 3099:3099
    volumes:
      - .:/app
    networks:
      br0:
        ipv4_address: 172.23.0.099

networks:
  br0:
    driver: bridge
    external: true
