version: '2.1'

services:
  nginx:
    image: nginx:1.25.4
    container_name: nginx
    volumes:
      - ./config/templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      # - NGINX_HOST=example.com
      - NGINX_PORT=80
    networks:
      - local

networks:
  local:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
