version: '2.1'

services:

  elastic:
    image: elasticsearch:8.13.0
    container_name: elastic
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:8.13.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elastic