version: '2.1'

services:
  mongodb:
    image: "bitnami/mongodb:7.0.8"
    # restart: always
    container_name: bitnami_mongodb
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=master
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - ./bitnami/mongodb:/bitnami/mongodb
