version: '2.1'

services:

  # That mongodb version fix problem:
  # "Prisma needs to perform transactions, which requires your MongoDB server to be run as a replica set" 
  bitnami_mongodb:
    image: "bitnami/mongodb:7.0.8"
    # restart: always
    container_name: bitnami_mongodb
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=master
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=example
    ports:
      - "27018:27017"
    volumes:
      - ./bitnami/mongodb:/bitnami/mongodb
    networks:
      mongo:
        ipv4_address: 172.23.2.20

networks:
  mongo:
    driver: bridge
    external: true
