version: "3.8"
services:
  mongodb:
    image: "bitnami/mongodb:latest"
    # restart: always
    container_name: bitnami_mongodb
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=master
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - "/var/lib/docker/bitnami_mongodb_data:/bitnami/mongodb"
